library(readr)
library(lubridate)
file <- "household_power_consumption.txt"
power <- read.csv( file = file ,sep=";")
power[,1]<-dmy(power[,1])
power<-subset(power,Date>="2007-02-01" & Date<="2007-02-02" )
power[,1]<-wday(power[,1],label=TRUE)
power[,3]<-as.numeric(power[,3])
power$Voltage<-as.numeric(power$Voltage)
par(mfrow=c(2,2))
with(power,{
	plot(ts(power[,3],start=5,end=7,frequency=1440),xlab="",ylab="Global Active Power (kilowatts)",xaxt="n")
	axis(1,at=seq_len(nrow(power)),label=nrow(power$Date))
	plot(ts(power$Voltage,start=5,end=7,frequency=1440),ylab="Voltage",xlab="datetime",xaxt="n")
	axis(1,at=seq_len(nrow(power)),label=nrow(power$Date))
	plot(ts(power$Sub_metering_1,start=5,end=7,frequency=1440),xlab="",ylab="Energy sub meeting",xaxt="n")
	lines(ts(power$Sub_metering_3,start=5,end=7,frequency=1440),xlab="",ylab="Energy sub meeting",xaxt="n",col="blue")
	lines(ts(power$Sub_metering_2,start=5,end=7,frequency=1440),xlab="",ylab="Energy sub meeting",xaxt="n",col="red")
	legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,cex=1.1)
	axis(1,at=seq_len(nrow(power)),label=nrow(power$Date)) 
	plot(ts(power[,4],start=5,end=7,frequency=1440),ylab="Global_Reactive_power",xlab="datetime",xaxt="n")
})
dev.copy(png,file="plot4.png")
dev.off()